### ISSUE TITLE
[Bug] Error 403, when I registered with GitHub and tried to shorten a link

### ISSUE THREAD

**Issue by solec0der** [jmesserli/short#1]
Steps to recreate:
* Create a user on pegnu keycloak using Github
* Go to https://short.peg.nu/
* Enter any link and click shorten

**Actual behaviour** 

I get a 403 Forbidden
<img width="1792" alt="Screenshot 2021-05-06 at 18 15 56" src="https://user-images.githubusercontent.com/34732976/117331918-83d4fb00-ae97-11eb-847e-80a2b1fd3ed9.png">

**Expected behaviour**

I can shorten a link :)

**Comment by jmesserli** [comment]
Hi, thank you for the report, but this is the expected behavior for my instance :)

There are quite many fishy users out there that tried to distribute malware/porn/etc. over my shortener.
Therefore, I need to manually assign a role on Keycloak, which I only do for trusted users; but since you are one of them, I've assigned the role to you.

Can you try again and report back if it works?

**Comment by solec0der** [comment]
Makes sense! Works like a charm! Thanks.
